name: Publish on Docker Hub and Deploy

on:
  release:
    types: [published]

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  build_and_pub:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
      PASSWORD: ${{ secrets.DOCKER_PWD }}
    steps:
      - name: Login to docker.io
        run: echo $PASSWORD | docker login -u $LOGIN --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME-train:${GITHUB_REF:11} -f Dockerfile_train .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME-train:${GITHUB_REF:11}